// packages/ui/src/components/input-color/input-color-picker.tsx
import { createSignal, type JSX, Show } from "solid-js";
import { createStore, unwrap } from "solid-js/store";
import { classnames } from "utils";

import { Button } from "../button/button";
import { InputRange } from "../input-range";
import { useColorContext } from "./input-color.context";
import { colorToString, DEFAULT_MODEL, getContrast } from "./input-color.helpers";
import { t } from "./input-color.translation";

import type { ColorModelHSL } from "../../types";

import styles from "./input-color.module.css";

interface Props extends JSX.HTMLAttributes<HTMLFieldSetElement> {
	onColorChange?: (model: ColorModelHSL) => void;
	opaque?: boolean;
}

export function InputColorPicker(props: Props) {
	const [ getRef, setRef ] = createSignal<HTMLFieldSetElement>();
	const [ color, setColor ] = createStore<ColorModelHSL>({ ...DEFAULT_MODEL });
	const { model, pickerID, setModel } = useColorContext();

	const handleClose = () => getRef()?.hidePopover();

	const handleSubmit = () => {
		const value = { ...unwrap(color) };
		setModel(value);
		props.onColorChange?.(value);
		handleClose();
	};

	const handleCancel = () => {
		setColor({ ...unwrap(model) });
		handleClose();
	};

	const getColor = () => colorToString(color);
	const colorContrast = () => getContrast(color);

	return (
		<fieldset class={classnames(styles.picker)} id={pickerID} popover="auto" ref={setRef}>
			<header class={styles["picker-header"]}>
				{t.HEADER}:
				<output
					class={styles["picker-swatch"]}
					style={{
						"--button-bg": getColor(),
						border: `4px solid ${colorContrast()}`
					}}
				/>
			</header>
			<InputRange
				label={t.HUE}
				max={360}
				min={0}
				onInput={event => setColor("h", event.target.valueAsNumber)}
				step={1}
				value={color.h}
			/>
			<InputRange
				label={t.SATURATION}
				max={100}
				min={0}
				onInput={event => setColor("s", event.target.valueAsNumber)}
				step={1}
				value={color.s}
			/>
			<InputRange
				label={t.LIGHTNESS}
				max={100}
				min={0}
				onInput={event => setColor("l", event.target.valueAsNumber)}
				step={1}
				value={color.l}
			/>
			<Show when={!props.opaque}>
				<InputRange
					label={t.OPACITY}
					max={100}
					min={0}
					onInput={event => setColor("o", event.target.valueAsNumber)}
					step={1}
					value={color.o}
				/>
			</Show>
			<footer class={styles["picker-footer"]}>
				<Button onClick={handleSubmit} wide>
					{t.SELECT}
				</Button>
				<Button
					appearance="outline"
					onClick={handleCancel}
					variant="danger"
					wide
				>
					{t.CANCEL}
				</Button>
			</footer>
		</fieldset>
	);
}

// src/lib/components/input-color/InputColorPicker.svelte
<script lang="ts" context="module">
	import type { Color } from "./input-color.types";
	import { colorDefault, convertColorToString } from "./input-color.helpers";
</script>

<script lang="ts">
	import { createEventDispatcher } from "svelte";
	import { Range } from "../input-range";
	import { Button } from "../button";
	import { trapFocus } from "$lib/actions";
	import { t } from "@core/i18n";
	import styles from "./input-color.module.css";

	export let className = "";
	export let element: HTMLFormElement | null = null;
	export let focusTrap = false;
	export let open = false;
	export let name: string;
	export let value = "hsl(0 50% 50% / 1)";
	export let valueAsObject: Color = colorDefault;

	const dispatch = createEventDispatcher();

	const handleCancel = () => {
		dispatch("cancel");
	};

	const handleSelect = () => {
		dispatch("select", valueAsObject);
	};

	const handleChange = (e: Event) => {
		e.stopImmediatePropagation();
	};

	$: value = convertColorToString(valueAsObject);
</script>

<form
	bind:this="{element}"
	class="{styles.form} {className}"
	on:change
	on:submit|preventDefault="{handleSelect}"
	style="
		--input-color-hue: {valueAsObject.hue};
		--input-color-saturation: {valueAsObject.saturation}%;
		--input-color-lightness: {valueAsObject.lightness}%;"
	use:trapFocus="{{
		active: focusTrap && open,
		selector: "input[type=range], button"
	}}"
>
	<header>
		{$t("component.color-input.header")}
		<output
			class="{styles.swatch}"
			style="--input-color-value: {value};"
		/>
	</header>
	<fieldset>
		<Range
			bind:value="{valueAsObject.hue}"
			className="{styles.hue}"
			name="{name}-hue"
			max="{360}"
			output
			on:change="{handleChange}"
		>
			{$t("component.color-input.hue")}
		</Range>
		<Range
			bind:value="{valueAsObject.saturation}"
			className="{styles.saturation}"
			name="{name}-saturation"
			output
			on:change="{handleChange}"
		>
			{$t("component.color-input.saturation")}
		</Range>
		<Range
			bind:value="{valueAsObject.lightness}"
			className="{styles.lightness}"
			name="{name}-lightness"
			output
			on:change="{handleChange}"
		>
			{$t("component.color-input.lightness")}
		</Range>
		<Range
			bind:value="{valueAsObject.opacity}"
			className="{styles.opacity}"
			max="{1}"
			name="{name}-opacity"
			output
			on:change="{handleChange}"
			step="{0.01}"
		>
			{$t("component.color-input.opacity")}
		</Range>
	</fieldset>
	<fieldset>
		<Button type="submit" appearance="ghost">
			{$t("component.color-input.select")}
		</Button>
		<Button type="button" on:click="{handleCancel}" appearance="ghost">
			{$t("component.color-input.cancel")}
		</Button>
	</fieldset>
</form>
