// src/content/sketch/chaos-game/src/ChaosGame.form.svelte
<script lang="ts">
	import InputRestrictions from "./ChaosGame.restrictions.svelte";
	import { InputColor, Range, SketchControls, Switch } from "@components";
	import { options, optionsImmutable } from "./chaos-game.options";

	export let t: Record<string, string>;
	export let state: typeof options = {
		...options
	};
</script>

<SketchControls bind:state on:reset {optionsImmutable} {options}>
	<fieldset>
		<legend>
			Polygon
		</legend>
		<Range
			output
			bind:value="{state["polygon-sides"]}"
			name="polygon-sides"
			min="{3}"
			max="{12}"
		>
			{t["polygon-sides"]}
		</Range>
		<Range
			output
			bind:value="{state["polygon-scale"]}"
			name="polygon-scale"
			min="{0.1}"
			max="{2}"
			step="{0.01}"
		>
			{t["polygon-scale"]}
		</Range>
		<Range
			output
			bind:value="{state["polygon-origin-theta"]}"
			name="polygon-origin-theta"
			min="{0}"
			max="{360}"
		>
			{t["polygon-origin-theta"]}
		</Range>
		<Range
			output
			bind:value="{state["polygon-line-width"]}"
			name="polygon-line-width"
			min="{0.5}"
			max="{5}"
			step="{0.5}"
			disabled="{!state["polygon-visible"]}"
		>
			{t["polygon-line-width"]}
		</Range>
		<Switch
			bind:checked="{state["polygon-visible"]}"
			name="polygon-visible"
		>
			{t["polygon-visible"]}
		</Switch>
		<InputColor
			bind:value="{state["polygon-color"]}"
			name="polygon-color"
			disabled="{!state["polygon-visible"]}"
		>
			{t["polygon-color"]}
		</InputColor>
	</fieldset>
	<fieldset>
		<legend>
			Marks
		</legend>
		<Range
			output
			bind:value="{state["points-limit"]}"
			name="points-limit"
			min="{1}"
			max="{500000}"
		>
			{t["points-limit"]}
		</Range>
		<Range
			output
			bind:value="{state["point-scale"]}"
			name="point-scale"
			min="{0.1}"
			max="{5}"
			step="{0.1}"
		>
			{t["point-scale"]}
		</Range>
		<Range
			output
			bind:value="{state["speed"]}"
			name="speed"
			min="{1}"
			max="{150}"
		>
			{t["speed"]}
		</Range>
		<Switch
			bind:checked="{state["points-color-wheel"]}"
			name="points-color-wheel"
		>
			{t["points-color-wheel"]}
		</Switch>
		<InputColor
			bind:value="{state["points-color"]}"
			name="points-color"
			disabled="{state["points-color-wheel"]}"
		>
			{t["polygon-color"]}
		</InputColor>
	</fieldset>
	<fieldset>
		<legend>
			Step
		</legend>
		<Switch
			bind:checked="{state["step-factor"]}"
			name="step-factor"
		>
			{t["step-factor"]}
		</Switch>
		<Range
			output
			bind:value="{state["step-coef"]}"
			disabled="{!state["step-factor"]}"
			name="step-coef"
			min="{0.01}"
			max="{1.5}"
			step="{0.01}"
		>
			{t["step-coef"]}
		</Range>
		<Range
			output
			bind:value="{state["step-distance"]}"
			disabled="{state["step-factor"]}"
			name="step-distance"
			min="{0.1}"
			max="{1000}"
			step="{0.1}"
		>
			{t["step-distance"]}
		</Range>
	</fieldset>
	<InputRestrictions
		bind:value="{state["restrictions"]}"
		sides="{state["polygon-sides"]}"
		{t}
	>
		{t["restrictions"]}
	</InputRestrictions>
</SketchControls>

// packages/escapist-marginalia/src/content/sketches/chaos-game/src/chaos-game.form.tsx
import { InputColor, InputRange, InputToggle } from "ui";

import { Fieldset, Form } from "~/layouts/sketch";

import { t } from "../translations";
import { useModel } from "./chaos-game.model";

interface Props {
	/**
	 * Reset renderer.
	 */
	onReset?: VoidFunction;
}

export function SketchForm(props: Props) {
	const { model, resetModel, setModel } = useModel();

	const handleReset = () => {
		resetModel();
		props.onReset?.();
	};

	return (
		<Form onReset={handleReset}>
			<Fieldset legend={t.POLYGON}>
				<InputToggle
					checked={model["polygon-visible"]}
					label={t.POLYGON_VISIBLE}
					onChange={event => {
						setModel("polygon-visible", event.target.checked);
						props.onReset?.();
					}}
				/>
				<InputRange
					label={t.POLYGON_SIDES}
					max={12}
					min={3}
					onChange={event => {
						setModel("polygon-sides", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={1}
					value={model["polygon-sides"]}
				/>
				<InputRange
					label={t.POLYGON_SCALE}
					max={2}
					min={0.1}
					onChange={event => {
						setModel("polygon-scale", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={0.01}
					value={model["polygon-scale"]}
				/>
				<InputRange
					label={t.POLYGON_ORIGIN_THETA}
					max={360}
					min={0}
					onChange={event => {
						setModel("polygon-origin-theta", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={0.01}
					value={model["polygon-scale"]}
				/>
				<InputRange
					disabled={!model["polygon-visible"]}
					label={t.POLYGON_LINE_WIDTH}
					max={5}
					min={0.5}
					onChange={event => {
						setModel("polygon-line-width", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={0.5}
					value={model["polygon-line-width"]}
				/>
				<InputColor
					disabled={model["polygon-visible"]}
					label={t.POLYGON_COLOR}
					onChange={({ valueAsString }) => {
						setModel("polygon-color", valueAsString);
						props.onReset?.();
					}}
					value={model["polygon-color"]}
				/>
			</Fieldset>
			<Fieldset legend={t.POINTS}>
				<InputRange
					label={t.POINTS_LIMIT}
					max={500000}
					min={10}
					onChange={event => {
						setModel("points-limit", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={1}
					value={model["points-limit"]}
				/>
				<InputRange
					label={t.POINT_SCALE}
					max={5}
					min={0.1}
					onChange={event => setModel("point-scale", event.target.valueAsNumber)}
					output
					step={0.1}
					value={model["point-scale"]}
				/>
				<InputRange
					label={t.SPEED}
					max={150}
					min={1}
					onChange={event => setModel("speed", event.target.valueAsNumber)}
					output
					step={1}
					value={model.speed}
				/>
				<InputToggle
					checked={model["points-color-wheel"]}
					label={t.POINTS_COLOR_WHEEL}
					onChange={event => {
						setModel("points-color-wheel", event.target.checked);
						props.onReset?.();
					}}
				/>
				<InputColor
					disabled={model["points-color-wheel"]}
					label={t.POINTS_COLOR}
					onChange={({ valueAsString }) => setModel("points-color", valueAsString)}
					value={model["points-color"]}
				/>
			</Fieldset>
			<Fieldset legend={t.STEP}>
				<InputToggle
					checked={model["step-factor"]}
					label={t.STEP_FACTOR}
					onChange={event => {
						setModel("step-factor", event.target.checked);
						props.onReset?.();
					}}
				/>
				<InputRange
					disabled={!model["step-factor"]}
					label={t.STEP_COEF}
					max={1.5}
					min={0.01}
					onChange={event => {
						setModel("step-coef", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={0.01}
					value={model["step-coef"]}
				/>
				<InputRange
					disabled={!model["step-factor"]}
					label={t.STEP_DISTANCE}
					max={1000}
					min={0.1}
					onChange={event => {
						setModel("step-distance", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={0.1}
					value={model["step-distance"]}
				/>
				{/* <InputRestrictions !reset
					bind:value="{state["restrictions"]}"
					sides="{state["polygon-sides"]}"
				>
					{t.RESTRICTIONS}
				</InputRestrictions> */}
			</Fieldset>
		</Form>
	);
}
