// src/core/ui/src/components/input-color/input-color.picker.svelte
<script lang="ts">
	import { createEventDispatcher } from "svelte";
	import { InputRange } from "../input-range";
	import { Button } from "../button";
	import { trapFocus } from "../../actions";
	import { colorDefault, convertColorToString } from "./input-color.helpers";
	import { t } from "./locale";
	import type { Color } from "./input-color.types";
	import styles from "./input-color.module.css";

	export let className = "";
	export let element: HTMLFormElement | null = null;
	export let focusTrap = false;
	export let locale: string = "en";
	export let open = false;
	export let name: string;
	export let value = "hsl(0 50% 50% / 1)";
	export let valueAsObject: Color = colorDefault;

	const dispatch = createEventDispatcher();

	const handleCancel = () => {
		dispatch("cancel");
	};

	const handleSelect = () => {
		dispatch("select", valueAsObject);
	};

	const handleChange = (e: Event) => {
		e.stopImmediatePropagation();
	};

	$: value = convertColorToString(valueAsObject);
</script>

<form
	bind:this="{element}"
	class="{styles.form} {className}"
	on:change
	on:submit|preventDefault="{handleSelect}"
	style="
		--input-color-hue: {valueAsObject.hue};
		--input-color-saturation: {valueAsObject.saturation}%;
		--input-color-lightness: {valueAsObject.lightness}%;"
	use:trapFocus="{{
		active: focusTrap && open,
		selector: "input[type=range], button"
	}}"
>
	<header>
		{t[locale].HEADER}
		<output
			class="{styles.swatch}"
			style="--input-color-value: {value};"
		/>
	</header>
	<fieldset>
		<InputRange
			bind:value="{valueAsObject.hue}"
			className="{styles.hue}"
			name="{name}-hue"
			max="{360}"
			output
			on:change="{handleChange}"
		>
			{t[locale].HUE}
		</InputRange>
		<InputRange
			bind:value="{valueAsObject.saturation}"
			className="{styles.saturation}"
			name="{name}-saturation"
			output
			on:change="{handleChange}"
		>
			{t[locale].SATURATION}
		</InputRange>
		<InputRange
			bind:value="{valueAsObject.lightness}"
			className="{styles.lightness}"
			name="{name}-lightness"
			output
			on:change="{handleChange}"
		>
			{t[locale].LIGHTNESS}
		</InputRange>
		<InputRange
			bind:value="{valueAsObject.opacity}"
			className="{styles.opacity}"
			max="{1}"
			name="{name}-opacity"
			output
			on:change="{handleChange}"
			step="{0.01}"
		>
			{t[locale].OPACITY}
		</InputRange>
	</fieldset>
	<fieldset>
		<Button type="submit" appearance="ghost">
			{t[locale].SELECT}
		</Button>
		<Button type="button" on:click="{handleCancel}" appearance="ghost">
			{t[locale].CANCEL}
		</Button>
	</fieldset>
</form>

// packages/ui/src/components/input-color/components/input-color-picker.tsx
import { createSignal, type JSX, Show } from "solid-js";
import { createStore, unwrap } from "solid-js/store";
import { classnames } from "utils";

import { Button } from "../../button/button";
import { InputRange } from "../../input-range";
import { getContrast, toColorString } from "../input-color.helpers";
import { t } from "../input-color.translation";

import type { ColorModelHSL } from "../../../types";
import type { InputChangeHandlerValue } from "../input-color";

import styles from "../input-color.module.css";

interface Props extends JSX.HTMLAttributes<HTMLFieldSetElement> {
	initialModel: ColorModelHSL;
	onColorChange?: (value: InputChangeHandlerValue) => void;
	opaque?: boolean;
	pickerID: string;
}

export function InputColorPicker(props: Props) {
	const [ getRef, setRef ] = createSignal<HTMLFieldSetElement>();
	const [ color, setColor ] = createStore<ColorModelHSL>({ ...unwrap(props.initialModel) });

	const handleClose = () => getRef()?.hidePopover();

	const handleSubmit = () => {
		const value = { ...unwrap(color) };
		props.onColorChange?.({
			value,
			valueAsString: toColorString(value)
		});
		handleClose();
	};

	const handleCancel = () => {
		handleClose();
	};

	const handleBeforeToggle = () => {
		setColor({ ...unwrap(props.initialModel) });
	};

	const getColor = () => toColorString(color);
	const colorContrast = () => getContrast(color);

	return (
		<fieldset
			class={classnames(styles.picker)}
			id={props.pickerID}
			onBeforeToggle={handleBeforeToggle}
			popover="auto"
			ref={setRef}
		>
			<header class={styles["picker-header"]}>
				{t.HEADER}:
				<output
					class={styles["picker-swatch"]}
					style={{
						"--button-bg": getColor(),
						border: `4px solid ${colorContrast()}`
					}}
				/>
			</header>
			<InputRange
				label={t.HUE}
				max={360}
				min={0}
				onInput={event => setColor("h", event.target.valueAsNumber)}
				output
				step={1}
				value={color.h}
			/>
			<InputRange
				label={t.SATURATION}
				max={100}
				min={0}
				onInput={event => setColor("s", event.target.valueAsNumber)}
				output
				step={1}
				value={color.s}
			/>
			<InputRange
				label={t.LIGHTNESS}
				max={100}
				min={0}
				onInput={event => setColor("l", event.target.valueAsNumber)}
				step={1}
				value={color.l}
			/>
			<Show when={!props.opaque}>
				<InputRange
					label={t.OPACITY}
					max={100}
					min={0}
					onInput={event => setColor("o", event.target.valueAsNumber)}
					output
					step={1}
					value={color.o}
				/>
			</Show>
			<footer class={styles["picker-footer"]}>
				<Button onClick={handleSubmit} wide>
					{t.SELECT}
				</Button>
				<Button
					appearance="outline"
					onClick={handleCancel}
					variant="danger"
					wide
				>
					{t.CANCEL}
				</Button>
			</footer>
		</fieldset>
	);
}
