// packages/ui/src/components/button/button.tsx
import { mergeProps, splitProps } from "solid-js";

import type { JSX } from "solid-js";

import { classnames, setAttr } from "../../utils";

import type { Appearance, Variant } from "../../types";

import styles from "./button.module.css";

export interface ButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
	appearance?: Exclude<Appearance, "text">;
	icon?: boolean;
	pending?: boolean;
	variant?: Variant;
	wide?: boolean;
}

const DEFAULT_PROPS: ButtonProps = {
	appearance: "fill",
	type: "button",
	variant: "accent"
};

export function Button(allProps: ButtonProps) {
	const mergedProps = mergeProps(DEFAULT_PROPS, allProps);
	const [ props, rest ] = splitProps(mergedProps, [
		"appearance",
		"children",
		"class",
		"icon",
		"pending",
		"variant",
		"wide"
	]);

	return (
		<button
			class={classnames(styles.button, props.class)}
			data-appearance={props.appearance}
			data-icon={setAttr(props.icon)}
			data-pending={setAttr(props.pending)}
			data-variant={props.variant}
			data-wide={setAttr(props.wide)}
			{...rest}
		>
			{props.children}
		</button>
	);
}

// src/core/ui/src/components/button/Button.svelte
<script lang="ts">
	import type { Appearance } from "./button.types";
	import styles from "./button.module.css";

	export let appearance: Appearance = "outline";
	export let className = "";
	export let disabled = false;
	export let id: string | undefined = undefined;
	export let icon = false;
	export let title: string | undefined = undefined;
	export let type: HTMLButtonElement["type"] = "button";
	export let wide = false;
</script>

<button
	class="{styles.button} {styles[appearance]} {className}"
	class:disabled
	class:icon
	class:wide
	{id}
	{type}
	{disabled}
	{title}
	on:click
	on:mousedown
	{...$$restProps}
>
	<slot />
</button>
