// src/apps/escapist-marginalia/src/content/sketch/geometric-hive/src/geometric-hive.form.svelte
<script lang="ts">
	import { getContext } from "svelte";
	import { InputColor, InputRange } from "ui";

	import { SketchControls } from "$lib/components";
	import { DEFAULT_OPTIONS, IMMUTABLE_OPTIONS } from "./geometric-hive.options";
	import type { Translation } from "../translations/types";

	export let state: typeof DEFAULT_OPTIONS = {
		...DEFAULT_OPTIONS
	};

	const t = getContext<Translation>("t");
</script>

<SketchControls
	bind:state
	on:reset
	options="{DEFAULT_OPTIONS}"
	optionsImmutable="{IMMUTABLE_OPTIONS}"
>
	<fieldset>
		<legend>
			{t.FIELD}
		</legend>
		<InputColor
			bind:value="{state["background"]}"
			name="background"
		>
			{t.BACKGROUND}
		</InputColor>
	</fieldset>
	<fieldset>
		<legend>
			{t.PARTICLES}
		</legend>
		<InputRange
			output
			bind:value="{state["particle-gap"]}"
			name="particle-gap"
			min="{1}"
			max="{4}"
			step="{0.01}"
		>
			{t.PARTICLE_GAP}
		</InputRange>
		<InputRange
			output
			bind:value="{state["particle-size"]}"
			name="particle-size"
			min="{5}"
			max="{40}"
		>
			{t.PARTICLE_SIZE}
		</InputRange>
		<InputRange
			output
			bind:value="{state["particle-speed-base"]}"
			name="particle-speed-base"
			min="{0.05}"
			max="{0.3}"
			step="{0.01}"
		>
			{t.PARTICLE_SPEED_BASE}
		</InputRange>
	</fieldset>
	<fieldset>
		<legend>
			{t.GAPS}
		</legend>
		<InputRange
			output
			bind:value="{state["gap-frequency"]}"
			name="gap-frequency"
			min="{0.80}"
			max="{0.97}"
			step="{0.01}"
		>
			{t.GAP_FREQUENCY}
		</InputRange>
	</fieldset>
</SketchControls>

// packages/escapist-marginalia/src/content/sketches/geometric-hive/src/geometric-hive.form.tsx
import { InputColor, InputRange } from "ui";

import { Fieldset, Form } from "~/layouts/sketch";

import { t } from "../translations";
import { useModel } from "./geometric-hive.model";

interface Props {
	/**
	 * Reset renderer.
	 */
	onReset?: VoidFunction;
}

export function SketchForm(props: Props) {
	const { model, resetModel, setModel } = useModel();

	const handleReset = () => {
		resetModel();
		props.onReset?.();
	};

	return (
		<Form onReset={handleReset}>
			<Fieldset legend={t.FIELD}>
				<InputColor
					label={t.BACKGROUND}
					onChange={({ valueAsString }) => setModel("background", valueAsString)}
					value={model.background}
				/>
			</Fieldset>
			<Fieldset legend={t.PARTICLES}>
				<InputRange
					label={t.PARTICLE_GAP}
					max={4}
					min={1}
					onChange={event => {
						setModel("particle-gap", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={0.01}
					value={model["particle-gap"]}
				/>
				<InputRange
					label={t.PARTICLE_SIZE}
					max={40}
					min={5}
					onChange={event => {
						setModel("particle-size", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={1}
					value={model["particle-size"]}
				/>
				<InputRange
					label={t.PARTICLE_SPEED_BASE}
					max={0.3}
					min={0.05}
					onChange={event => {
						setModel("particle-speed-base", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={0.01}
					value={model["particle-speed-base"]}
				/>
			</Fieldset>
			<Fieldset legend={t.GAPS}>
				<InputRange
					label={t.GAP_FREQUENCY}
					max={0.97}
					min={0.8}
					onChange={event => {
						setModel("gap-frequency", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={0.01}
					value={model["gap-frequency"]}
				/>
			</Fieldset>
		</Form>
	);
}
