// packages/escapist-marginalia/src/content/sketches/flocking/src/flocking.form.tsx
import { InputRange, InputToggle } from "ui";

import { Fieldset, Form } from "~/layouts/sketch";

import { t } from "../translations";
import { useModel } from "./flocking.model";

interface Props {
	/**
	 * Reset renderer.
	 */
	onReset?: VoidFunction;
}

export function SketchForm(props: Props) {
	const { model, resetModel, setModel } = useModel();

	const handleReset = () => {
		resetModel();
		props.onReset?.();
	};

	return (
		<Form onReset={handleReset}>
			<Fieldset legend={t.BEHAVIOR}>
				<InputRange
					label={t.BOIDS}
					max={250}
					min={10}
					onChange={event => {
						setModel("boids", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={1}
					value={model.boids}
				/>
				<InputToggle
					checked={model.bound}
					label={t.BOUND}
					onChange={event => setModel("bound", event.target.checked)}
				/>
				<InputRange
					label={t.ALIGNMENT}
					max={2.5}
					min={0.1}
					onChange={event => setModel("align", event.target.valueAsNumber)}
					output
					step={0.01}
					value={model.align}
				/>
				<InputRange
					label={t.COHESION}
					max={2}
					min={0.01}
					onChange={event => setModel("cohesion", event.target.valueAsNumber)}
					output
					step={0.01}
					value={model.cohesion}
				/>
				<InputRange
					label={t.SEPARATION}
					max={2.5}
					min={0.1}
					onChange={event => setModel("separate", event.target.valueAsNumber)}
					output
					step={0.01}
					value={model.separate}
				/>
			</Fieldset>
			<Fieldset legend={t.APPEARANCE}>
				<InputRange
					label={t.SCALE}
					max={5}
					min={1}
					onChange={event => {
						setModel("scale", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={0.1}
					value={model.scale}
				/>
			</Fieldset>
			<Fieldset legend={t.QTREE}>
				<InputToggle
					checked={model.qtree}
					label={t.QTREE_OPTIMIZATION}
					onChange={event => setModel("qtree", event.target.checked)}
				/>
				<InputToggle
					checked={model.showQTree}
					disabled={!model.qtree}
					label={t.QTREE_APPEARANCE}
					onChange={event => setModel("showQTree", event.target.checked)}
				/>
				<InputToggle
					checked={model.showPerception}
					disabled={!model.qtree}
					label={t.PERCEPTION_APPEARANCE}
					onChange={event => setModel("showPerception", event.target.checked)}
				/>
				<InputRange
					label={t.PERCEPTION}
					max={250}
					min={50}
					onChange={event => setModel("perception", event.target.valueAsNumber)}
					output
					step={1}
					value={model.perception}
				/>
			</Fieldset>
		</Form>
	);
}

// src/apps/escapist-marginalia/src/content/sketch/flocking/src/flocking.form.svelte
<script lang="ts">
	import { getContext } from "svelte";
	import { InputRange, InputSwitch } from "ui";

	import { SketchControls } from "$lib/components";
	import { DEFAULT_OPTIONS, IMMUTABLE_OPTIONS } from "./flocking.options";
	import type { Translation } from "../translations/types";

	const t = getContext<Translation>("t");

	export let state: typeof DEFAULT_OPTIONS = {
		...DEFAULT_OPTIONS
	};
</script>

<SketchControls
	bind:state
	on:reset
	options="{DEFAULT_OPTIONS}"
	optionsImmutable="{IMMUTABLE_OPTIONS}"
>
	<fieldset>
		<legend>
			{t.BEHAVIOR}
		</legend>
		<InputRange output bind:value="{state.boids}" name="boids" min="{10}" max="{250}">
			{t.BOIDS}
		</InputRange>
		<InputSwitch bind:checked="{state.bound}" name="bound">
			{t.BOUND}
		</InputSwitch>
		<InputRange output bind:value="{state.align}" name="align" min="{0.1}" max="{2.5}" step="{0.01}">
			{t.ALIGNMENT}
		</InputRange>
		<InputRange output bind:value="{state.cohesion}" name="cohesion" min="{0.01}" max="{2}" step="{0.01}">
			{t.COHESION}
		</InputRange>
		<InputRange output bind:value="{state.separate}" name="separate" min="{0.1}" max="{2.5}" step="{0.01}">
			{t.SEPARATION}
		</InputRange>
	</fieldset>
	<fieldset>
		<legend>
			{t.APPEARANCE}
		</legend>
		<InputRange output bind:value="{state.scale}" name="scale" min="{1}" max="{5}" step="{0.1}">
			{t.SCALE}
		</InputRange>
	</fieldset>
	<fieldset>
		<legend>
			{t.QTREE}
		</legend>
		<InputSwitch bind:checked="{state.qtree}" name="qtree">
			{t.QTREE_OPTIMIZATION}
		</InputSwitch>
		<InputSwitch bind:checked="{state.showQTree}" disabled="{!state.qtree}" name="showQTree">
			{t.QTREE_APPEARANCE}
		</InputSwitch>
		<InputSwitch bind:checked="{state.showPerception}" disabled="{!state.qtree}" name="showPerception">
			{t.PERCEPTION_APPEARANCE}
		</InputSwitch>
		<InputRange output bind:value="{state.perception}" disabled="{!state.qtree}" name="perception" min="{50}" max="{250}">
			{t.PERCEPTION}
		</InputRange>
	</fieldset>
</SketchControls>
