// src/content/sketch/flocking/src/Flocking.form.svelte
<script lang="ts">
	import { Switch, Range, SketchControls } from "@components";
	import { options, optionsImmutable } from "./flocking.options";

	export let t: Record<string, string>;
	export let state: typeof options = {
		...options
	};
</script>

<SketchControls bind:state on:reset {optionsImmutable} {options}>
	<fieldset>
		<legend>
			{t.behavior}
		</legend>
		<Range output bind:value="{state.boids}" name="boids" min="{10}" max="{250}">
			{t.boids}
		</Range>
		<Switch bind:checked="{state.bound}" name="bound">
			{t.bound}
		</Switch>
		<Range output bind:value="{state.align}" name="align" min="{0.1}" max="{2.5}" step="{0.01}">
			{t.alignment}
		</Range>
		<Range output bind:value="{state.cohesion}" name="cohesion" min="{0.01}" max="{2}" step="{0.01}">
			{t.cohesion}
		</Range>
		<Range output bind:value="{state.separate}" name="separate" min="{0.1}" max="{2.5}" step="{0.01}">
			{t.separation}
		</Range>
	</fieldset>
	<fieldset>
		<legend>
			{t.appearance}
		</legend>
		<Range output bind:value="{state.scale}" name="scale" min="{1}" max="{5}" step="{0.1}">
			{t.scale}
		</Range>
	</fieldset>
	<fieldset>
		<legend>
			{t.quadtree}
		</legend>
		<Switch bind:checked="{state.qtree}" name="qtree">
			{t["qtree-optimization"]}
		</Switch>
		<Switch bind:checked="{state.showQTree}" disabled="{!state.qtree}" name="showQTree">
			{t["qtree-appearance"]}
		</Switch>
		<Switch bind:checked="{state.showPerception}" disabled="{!state.qtree}" name="showPerception">
			{t["perception-appearance"]}
		</Switch>
		<Range output bind:value="{state.perception}" disabled="{!state.qtree}" name="perception" min="{50}" max="{250}">
			{t.perception}
		</Range>
	</fieldset>
</SketchControls>

// packages/escapist-marginalia/src/content/sketches/flocking/src/flocking.form.tsx
import { InputRange, InputToggle } from "ui";

import { Fieldset, Form } from "~/layouts/sketch";

import { t } from "../translations";
import { useModel } from "./flocking.model";

interface Props {
	/**
	 * Reset renderer.
	 */
	onReset?: VoidFunction;
}

export function SketchForm(props: Props) {
	const { model, resetModel, setModel } = useModel();

	const handleReset = () => {
		resetModel();
		props.onReset?.();
	};

	return (
		<Form onReset={handleReset}>
			<Fieldset legend={t.BEHAVIOR}>
				<InputRange
					label={t.BOIDS}
					max={250}
					min={10}
					onChange={event => {
						setModel("boids", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={1}
					value={model.boids}
				/>
				<InputToggle
					checked={model.bound}
					label={t.BOUND}
					onChange={event => setModel("bound", event.target.checked)}
				/>
				<InputRange
					label={t.ALIGNMENT}
					max={2.5}
					min={0.1}
					onChange={event => setModel("align", event.target.valueAsNumber)}
					output
					step={0.01}
					value={model.align}
				/>
				<InputRange
					label={t.COHESION}
					max={2}
					min={0.01}
					onChange={event => setModel("cohesion", event.target.valueAsNumber)}
					output
					step={0.01}
					value={model.cohesion}
				/>
				<InputRange
					label={t.SEPARATION}
					max={2.5}
					min={0.1}
					onChange={event => setModel("separate", event.target.valueAsNumber)}
					output
					step={0.01}
					value={model.separate}
				/>
			</Fieldset>
			<Fieldset legend={t.APPEARANCE}>
				<InputRange
					label={t.SCALE}
					max={5}
					min={1}
					onChange={event => {
						setModel("scale", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={0.1}
					value={model.scale}
				/>
			</Fieldset>
			<Fieldset legend={t.QTREE}>
				<InputToggle
					checked={model.qtree}
					label={t.QTREE_OPTIMIZATION}
					onChange={event => setModel("qtree", event.target.checked)}
				/>
				<InputToggle
					checked={model.showQTree}
					disabled={!model.qtree}
					label={t.QTREE_APPEARANCE}
					onChange={event => setModel("showQTree", event.target.checked)}
				/>
				<InputToggle
					checked={model.showPerception}
					disabled={!model.qtree}
					label={t.PERCEPTION_APPEARANCE}
					onChange={event => setModel("showPerception", event.target.checked)}
				/>
				<InputRange
					label={t.PERCEPTION}
					max={250}
					min={50}
					onChange={event => setModel("perception", event.target.valueAsNumber)}
					output
					step={1}
					value={model.perception}
				/>
			</Fieldset>
		</Form>
	);
}
