// packages/escapist-marginalia/src/content/sketches/the-attractor/src/the-attractor.form.tsx
import { InputRange } from "ui";

import { Fieldset, Form } from "~/layouts/sketch";

import { t } from "../translations";
import { useModel } from "./the-attractor.model";

interface Props {
	onReset?: VoidFunction;
}

export function SketchForm(props: Props) {
	const { model, resetModel, setModel } = useModel();

	const handleReset = () => {
		resetModel();
		props.onReset?.();
	};

	return (
		<Form onReset={handleReset}>
			<Fieldset legend={t.FIELD}>
				<InputRange
					label={t.ATTRACTORS}
					max={15}
					min={1}
					onChange={event => {
						setModel("attractors", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={1}
					value={model.attractors}
				/>
			</Fieldset>
			<Fieldset legend={t.PARTICLES}>
				<InputRange
					label={t.COUNT}
					max={2500}
					min={500}
					onChange={event => {
						setModel("particles", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={1}
					value={model.particles}
				/>
				<InputRange
					label={t.LIFETIME}
					max={3000}
					min={250}
					onChange={event => {
						setModel("lifetime", event.target.valueAsNumber);
						props.onReset?.();
					}}
					output
					step={1}
					value={model.lifetime}
				/>
			</Fieldset>
		</Form>
	);
}

// src/apps/escapist-marginalia/src/content/sketch/the-attractor/src/the-attractor.form.svelte
<script lang="ts">
	import { InputRange } from "ui";

	import { SketchControls } from "@components";
	import { options, optionsImmutable } from "./the-attractor.options";

	export let t: Record<string, string>;
	export let state: typeof options = {
		...options
	};
</script>

<SketchControls bind:state on:reset {optionsImmutable} {options}>
	<fieldset>
		<legend>
			{t.field}
		</legend>
		<InputRange output bind:value="{state.attractors}" name="attractors" min="{1}" max="{15}">
			{t.attractors}
		</InputRange>
	</fieldset>
	<fieldset>
		<legend>
			{t.particles}
		</legend>
		<InputRange output bind:value="{state.particles}" name="particles" min="{500}" max="{2500}">
			{t.count}
		</InputRange>
		<InputRange output bind:value="{state.lifetime}" name="lifetime" min="{250}" max="{3000}">
			{t.lifetime}
		</InputRange>
	</fieldset>
</SketchControls>
